name: Android CI

on:
  push:
    branches:
      - develop

env:
  base_url: ${{ secrets.BASE_URL }}
  password: ${{ secrets.PASSWORD }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.1
        with:
          files: |
            .github/workflows/pr_ci.yml
            gradle/libs.versions.toml
            **/*.kt
            **/*.kts
            **/*.xml

  check-codestyle:
    needs: [ file-changes ]
    runs-on: ubuntu-latest
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.8.0
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Check codestyle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: spotlessCheck
          gradle-home-cache-cleanup: true

  unit-tests:
    needs: [ check-codestyle ]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.8.0
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: test
          gradle-home-cache-cleanup: true

      - name: (Fail-only) Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Unit tests report
          path: app/build/reports/tests/

  build-apks:
    needs: [ check-codestyle ]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}"/app/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 --decode > "${TMP_KEYSTORE_FILE_PATH}"/qbit-key.jks

      - name: Set up JDK
        uses: actions/setup-java@v3.8.0
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Build signed APKs
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: assembleRelease
          gradle-home-cache-cleanup: true
        env:
          GITHUB_CI: true
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload signed APKs
        uses: actions/upload-artifact@v3
        with:
          name: Signed APKs
          path: app/build/outputs/apk/release/*.apk
